abbr --add cat bat
abbr --add cp "cp -iv "
abbr --add eh "emacs ~/repo/dotfiles/hyprland/hyprland.conf"
abbr --add ff "clear && fastfetch"
abbr --add htop "btop "
#abbr --add kcc  "kanata --check -c ~/repo/dotfiles/kanata/kanata-miryoku.kbd" # Kanata Check Config
#abbr --add krs  "systemctl --user restart kanata-custom.service" # Kanata Restart Service
#abbr --add KKK  "pkill kanata | kanata -c ~/repo/dotfiles/kanata/kanata-miryoku.kbd"
abbr --add l "eza --long --all --header --group-directories-first --color=always "
abbr --add la "eza --long --all --header --git --group-directories-first --color=always "
abbr --add lg "eza --long --all --header --grid --smart-group --color=always"
abbr --add lt "eza --long --all --header --group --tree --group-directories-first --color=always --level=2 "
abbr --add lz lazygit
abbr --add mkdir "mkdir -pv "
abbr --add mv "mv -iv "
#abbr --add nfu  "nix flake update &| nom "
#abbr --add nfud  "nix flake update localDots --flake /etc/nixos &| nom"
#abbr --add nhs  "nh home switch --ask"
#abbr --add nhfs  "nh home switch "
#abbr --add nhsf  "nh home switch "
#abbr --add nhsu  "nh home switch --ask --update"
#abbr --add nhsuf  "nh home switch --update"
#abbr --add nos  "nh os switch --ask"
#abbr --add nosf  "nh os switch "
#abbr --add nosu  "nh os switch --ask --update"
#abbr --add nosuf  "nh os switch --update"
abbr --add pk "pkill -e "
abbr --add pkill "pkill -e "
abbr --add rm "rm -iv "
#abbr --add sa  "ssh-add"
abbr --add sofi ". ~/.config/fish/config.fish"
#abbr --add vi  "neovide "
abbr --add z "cd "
abbr --add zi "cdi "
