keybinding:
  universal:
    quit: q
    quit-alt1: <Esc>
    return: <C-c>
    quitWithoutChangingDirectory: Q
    togglePanel: <tab>
    prevItem: <up>
    nextItem: <down>
    prevItem-alt: k
    nextItem-alt: j
    prevPage: ","
    nextPage: .
    scrollLeft: H
    scrollRight: L
    gotoTop: <
    gotoBottom: >
    prevBlock: <left>
    nextBlock: <right>
    prevBlock-alt: h
    nextBlock-alt: l
    nextBlock-alt2: <tab>
    prevBlock-alt2: <backtab>
    nextMatch: n
    prevMatch: N
    startSearch: /
    optionMenu: ""
    optionMenu-alt1: "?"
    select: <space>
    goInto: <enter>
    confirm: <enter>
    confirmInEditor: <a-enter>
    remove: d
    new: n
    edit: e
    openFile: o
    scrollUpMain: <pgup>
    scrollDownMain: <pgdown>
    scrollUpMain-alt1: K
    scrollDownMain-alt1: J
    scrollUpMain-alt2: <c-u>
    scrollDownMain-alt2: <c-d>
    executeCustomCommand: ":"
    createRebaseOptionsMenu: m
    pushFiles: P
    pullFiles: p
    refresh: R
    createPatchOptionsMenu: <c-p>
    nextTab: "]"
    prevTab: "["
    nextScreenMode: +
    prevScreenMode: _
    undo: z
    redo: <c-z>
    filteringMenu: <c-s>
    diffingMenu: W
    diffingMenu-alt: <c-e>
    copyToClipboard: <c-o>
    openRecentRepos: <c-r>
    submitEditorText: <enter>
    extrasMenu: "@"
    toggleWhitespaceInDiffView: <c-w>
    increaseContextInDiffView: "}"
    decreaseContextInDiffView: "{"
