preload = ~/.config/wallpapers/nord-lake.png
preload = ~/.config/wallpapers/1330238.png

wallpaper = ,~/.config/wallpapers/nord-lake.png
wallpaper = ,~/.config/wallpapers/1330238.png

splash=true

# ipc=off
