#+TITLE: dobin's emacs config
#+AUTHOR: hyeondobin
#+PROPERTY: header-args :tangle init.el :tangle-mode: #o444 :noweb yes :mkdirp yes

* Emacs 설정
 기존의 설정을 설명을 붙여놓은 파일을 만들어둬야 나중에 까먹지 않을 것 같아서 만든 파일.

* Elpaca bootstrap
 기본적인 elpaca 설치 및 설정을 한다. elpaca는 패키지 매니저로 각종 플러그인이라고도 할 수 있는 패키지들을 다운로드 받고 설정할 수 있으며 이맥스 자체의 설정도 같이 할 수 있다.
 또 다른 패키지 매니저인 =use-package= 와 연계하여 사용할 수 있어서 그렇게 사용 중이다.

 :ensure t를 해주면 elpaca가 온라인(elpa, melpa 등)에서 패키지를 다운로드 받는다.
 nil일 시에는 다운로드 받지 않고 로컬에서 불러온다.
 :ensure (:wait t) 를 하면 해당 패키지의 로딩이 끝날 때까지 다른 패키지를 로드하지 않고 기다린다.

#+begin_src emacs-lisp :lexical t
  ;; bootstrap elpaca
  (defvar elpaca-installer-version 0.11)
  (defvar elpaca-directory (expand-file-name "elpaca/" user-emacs-directory))
  (defvar elpaca-builds-directory (expand-file-name "builds/" elpaca-directory))
  (defvar elpaca-repos-directory (expand-file-name "repos/" elpaca-directory))
  (defvar elpaca-order '(elpaca :repo "https://github.com/progfolio/elpaca.git"
                            :ref nil :depth 1 :inherit ignore
                            :files (:defaults "elpaca-test.el" (:exclude "extensions"))
                            :build (:not elpaca--activate-package)))
  (let* ((repo  (expand-file-name "elpaca/" elpaca-repos-directory))
            (build (expand-file-name "elpaca/" elpaca-builds-directory))
            (order (cdr elpaca-order))
            (default-directory repo))
      (add-to-list 'load-path (if (file-exists-p build) build repo))
      (unless (file-exists-p repo)
          (make-directory repo t)
          (when (<= emacs-major-version 28) (require 'subr-x))
          (condition-case-unless-debug err
              (if-let* ((buffer (pop-to-buffer-same-window "*elpaca-bootstrap*"))
                           ((zerop (apply #'call-process `("git" nil ,buffer t "clone"
                                                              ,@(when-let* ((depth (plist-get order :depth)))
                                                                    (list (format "--depth=%d" depth) "--no-single-branch"))
                                                              ,(plist-get order :repo) ,repo))))
                           ((zerop (call-process "git" nil buffer t "checkout"
                                       (or (plist-get order :ref) "--"))))
                           (emacs (concat invocation-directory invocation-name))
                           ((zerop (call-process emacs nil buffer nil "-Q" "-L" "." "--batch"
                                       "--eval" "(byte-recompile-directory \".\" 0 'force)")))
                           ((require 'elpaca))
                           ((elpaca-generate-autoloads "elpaca" repo)))
                  (progn (message "%s" (buffer-string)) (kill-buffer buffer))
                  (error "%s" (with-current-buffer buffer (buffer-string))))
              ((error) (warn "%s" err) (delete-directory repo 'recursive))))
      (unless (require 'elpaca-autoloads nil t)
          (require 'elpaca)
          (elpaca-generate-autoloads "elpaca" repo)
          (let ((load-source-file-function nil)) (load "./elpaca-autoloads"))))
  (add-hook 'after-init-hook #'elpaca-process-queues)
  (elpaca `(,@elpaca-order))

  (elpaca elpaca-use-package
      (elpaca-use-package-mode))

#+end_src

* emacs 기본 설정들

emacs의 기본적인 설정들. 그냥 ~setq~ 나 ~setopt~ 를 단독으로 사용하는 대신 ~(use-package emacs ...)~ 을 사용하여 설정한다.

#+begin_src emacs-lisp :lexical t
  (use-package emacs
      :demand t
      :ensure nil
      :custom
      (enable-recursive-minibuffers +1)
      (backup-by-copying +1)
      (sentence-end-double-space nil)
      (frame-inhibit-implied-resize t) ;; tiling window manager에서는 필요가 없음
      (show-trailing-whitespace t)
      (ring-bell-function -1)
      (inhibit-startup-message t)
      (use-short-answers t)

      (user-full-name "Jehui Lee")
      (user-mail-address "jayli2558@gmail.com")

      (display-line-numbers 'visual)
      (save-place-mode +1)

      (indent-tabs-mode nil)
      (tab-width 4)
      (lisp-indent-offset 4)

      (help-window-select t)
      (create-lockfiles nil)
      (backup-directory-alist
          `((".*" . ,(concat user-emacs-directory "backups")))
          auto-save-file-name-transforms
          `((".*" ,(concat user-emacs-directory "backups") t)))
      (custom-safe-themes t) ; mark all themes as safe
      (enable-local-variables :all) ; fix =defvar= warnings

      (delete-by-moving-to-trash t)

      (byte-compile-warnings '(not free-vars unresolved noruntime lexical make-local)) ; elisp 컴파일 시의 경고 메세지 줄이기.
      (native-comp-async-report-warnings-errors nil)
      (load-prefer-newer t)

      (custom-file "~/repo/dotfiles/emacs/customs.el")

      :init
      (global-visual-line-mode +1) ; 보이는 그대로의 라인으로 이동을 한다. wrapping이 되어도 된 줄을 기준으로 이동한다.

      (set-charset-priority 'unicode) ;; utf-8 everywhere
      (set-language-environment "Korean") ; 한글관련 세팅인데 뭐지 잘 모르겠음
      (prefer-coding-system 'utf-8)
      (set-default-coding-systems 'utf-8)

      (global-set-key (kbd "<escape>") 'dobin/keyboard-quit) ;; ESC를 메타 프리픽스로 사용하지 않는다.

      :hook
      (before-save . delete-trailing-whitespace) ; 저장 시 남은 공백 제거
      )
#+end_src

** 변수 | variables

변수들 설정.

#+begin_src emacs-lisp :lexical t
  (defvar dobin/notes-path "~/repo/org/roam" "Notes.")

  (defvar dobin/journal-path (concat dobin/notes-path "daily/")
     "Journal entries" )

  (defvar dobin/org-path "~/repo/org/" "Org path.")
#+end_src

* Package
패키지 혹은 플러그인이라고도 할 수 있는 파일들을 로드하고 설정한다. 다양한 추가기능이나 테마 등이 패키지에 속한다고 볼 수 있다.

** dired
파일 탐색기

#+begin_src emacs-lisp :lexical t
  (use-package dired
      :ensure nil
      :custom
      (dired-auto-revert-buffer 'dired-directory-changed-p)
      (dired-kill-when-opening-new-dired-buffer t)
      )
#+end_src

** evil
emacs에서 vi motion을 사용할 수 있게 해주는 패키지. 이 패키지가 없었다면 아마 emacs를 시도하지 않았을 것이다.

*** evil
본체. 핵심이다.
#+begin_src emacs-lisp :lexical t
  (use-package evil
      :ensure t
      :demand t
      :custom
      (evil-cross-lines t)
      (evil-highlight-closing-paren-at-point-states '(not emacs replace))
      (evil-respect-visual-line-mode t) ; 보이는 그대로 라인 판정
      (evil-search-module 'isearch)

      (evil-undo-system 'undo-redo) ; emacs 28부터 있는 undo-redo를 사용하여 redo활성화

      ;; 이동 관련
      (evil-want-C-i-jump t)
      (evil-want-C-d-scroll t)
      (evil-want-C-u-scroll t)

      (evil-split-window-below t) ; split으로 생긴 창을 아래쪽으로
      (evil-vsplit-window-right t); split으로 생긴 창을 오른쪽으로

      :init
      (setopt evil-want-integration t) ; evil-collection의 필요 설정
      (setopt evil-want-keybinding nil)
      :config
      (evil-mode t)
      ;; 기본 시작을 노멀모드로 설정할 버퍼들
      (evil-set-initial-state 'messages-buffer-mode 'normal)
      (evil-set-initial-state 'dashboard-mode 'normal)
      ;; insert 모드로 시작할 버퍼들
      (evil-set-initial-state 'eshell-mode 'insert)
      (evil-set-initial-state 'magit-diff-mode 'insert)
      )
#+end_src

*** evil-collection
여러가지 모드에서 사용하는 keymap에서 evil을 지원하게 한다. 일일이 설정해야하는 것을 사람들이 설정하여
공유해 놓은 말 그대로 컬렉션이다.

#+begin_src emacs-lisp :lexical t
    (use-package evil-collection
      :after evil
      :custom
      (evil-collection-setup-minibuffer t)
      (evil-collection-want-find-usages-bindings t)
      :demand t
      :ensure t
      :config
      (evil-collection-init))

#+end_src

*** evil-commentary
코멘트를 evil-motion을 사용하여 만들 수 있게 해주는 패키지. vim-commentary의 evil버전이라고 보면 된다.
| prefix     | 명령어                |
|------------+----------------------|
| gc         | evil-commentary      |
| gy         | evil-commentary-yank |
| s(super)-/ | evil-commentary-line |

#+begin_src emacs-lisp :lexical t
  (use-package evil-commentary
      :after evil
      :ensure t
      :config
      (evil-commentary-mode))

#+end_src

*** evil-surrounding
=""= 이나 =()= 같은 감싸고 있는 객체를 제어할 수 있는 모션 추가
| mode   | prefix       | 작업                 |
|--------+--------------+---------------------|
| visual | ~S~ or ~gS~  | surrounding 추가     |
| normal | ~ys~ or ~yS~ | surrounding 추가     |
| both   | cs<old><new> | <old>를 <new>로 변경 |
| both   | ds           | surrounding 제거     |

#+begin_src emacs-lisp :lexical t
  (use-package evil-surround
      :after evil
      :ensure t
      :config
      (global-evil-surround-mode t))

#+end_src

*** evil-goggles
evil motion에 대한 visual 힌트를 제공
어떤 모션을 실행했을 때 그 모션이 적용이 되는 범위를 한 번 하이라이트 해서 보여준다.

#+begin_src emacs-lisp :lexical t
  (use-package evil-goggles
      :ensure t
      :config
      (evil-goggles-mode)
      (evil-goggles-use-diff-faces))
#+end_src

*** TODO evil-owl
register관련 패키지. 일단 받아보기는 했는데 추가로 확인을 해야한다.

#+begin_src emacs-lisp :lexical t
    (use-package evil-owl
      :ensure t
      :diminish ""
      ;; :config
      )
#+end_src

*** TODO evil-org
org모드와 evil을 연계시켜주는 패키지라고 하는데 얘도 자세한 내용을 확인해보지는 않았다.

#+begin_src emacs-lisp :lexical t
  (use-package evil-org
      :ensure t
      :after org
      :hook (org-mode . (lambda () evil-org-mode))
      :config
      (require 'evil-org-agenda)
      (evil-org-agenda-set-keys))
#+end_src

** desktop
session을 저장했다가 불러오는 기능인 듯한데 daemon으로 썼을 때는 저장이 안되는 것 같다. 정확한 사용법을 알아볼 필요가 있다. 그 전까지는 일단 활성화하지 않는다.

#+begin_src emacs-lisp :lexical t :tangle no
  (use-package desktop
      :ensure nil
      :config
      (desktop-save-mode +1))
#+end_src

** electric
정확히 무슨 기능을 하는 패키지인지는 모르겠지만 일단 괄호나 따옴표의 짝을 맞춰주는 기능이 있다.

#+begin_src emacs-lisp :lexical t
  (use-package electric
      :demand t
      :ensure nil
      :init
      (electric-pair-mode t)
      (setopt electric-pair-preserve-balance t))
#+end_src

** TODO ediff
diff라고 해서 넣어놓긴 했는데 자세한 기능을 모른다. 얘도 알아봐야할 듯
#+begin_src emacs-lisp :lexical t
    (use-package ediff
      :demand t
      :ensure nil)
#+end_src

** general
키 매핑을 쉽게 해주는 패키지. evil과 연계가 잘 되어있어서 leader 매핑을 쉽게 만들 수 있다.
:general을 사용해서 use-package에서도 키워드로 사용할 수 있다.

#+begin_src emacs-lisp :lexical t
  (use-package general
      :ensure (:wait t)
      :demand t
      :config
      (general-evil-setup) ;; general과 evil 연계

      ;; leader key로 'space'를 사용
      (general-create-definer dobin/leader-keys
          :states '(normal insert visual emacs)
          :keymaps 'override
          :prefix "SPC" ;; leader 설정
          :global-prefix "M-SPC") ;; insert 모드에서의 리더키

      ;; local leader key로 ','를 사용
      (general-create-definer dobin/local-leader-keys
          :states '(normal insert visual emacs)
          :keymaps 'override
          :prefix "," ;; leader 설정
          :global-prefix "M-,") ;; insert 모드에서의 로컬 리더키

      (general-define-key
          :states 'insert
          "C-g" 'dobin/keyboard-quit)

      (general-define-key
          :keymaps '(minibuffer-mode-map minibuffer-local-map)
          :states '(normal insert emacs)
          "ESC" 'dobin/keyboard-quit)

      (general-unbind
          "C-x C-r" ;; find-file read only 비활성화
          "C-x C-z" ;; suspend frame 비활성화
          "C-x C-d" ;; list directory 비활성화
          "<mouse-2>") ;; 마우스 휠 클릭으로 붙여넣기 비활성화

      (dobin/leader-keys
          "SPC" '(execute-extended-command :wk "command 실행") ;; M-x 대체
          "TAB" '(:keymap tab-prefix-map :wk "[t]ab")) ;; tab 단축키 리맵
      (general-define-key
          "M-w" 'dobin/save-and-kill-buffer)

      ;; help
      (dobin/leader-keys
          "h" '(:ignore t :wk "[h]elp"))

      ;; search
      (dobin/leader-keys
          "s" '(:wk "[s]earch" :ignore t))

      ;; file
      (dobin/leader-keys
          "f" '(:ignore t :wk "[f]ile")
          "fc" '(:ignore t :wk "[c]onfig")
          "fci" '((lambda () (interactive) (find-file (concat user-emacs-directory "config.org"))) :wk "[i]nit file(사실 config.org)")
          "fcr" '(dobin/restart-server :wk "[r]eload")
          "fd" '(dired-jump :wk "[d]ired")
          "ff" '(find-file :wk "[f]ind [f]ile")
          "fs" '(save-buffer :wk "[s]ave"))

      ;; buffer
      (dobin/leader-keys
          "b" '(:ignore t :wk "[b]uffer")
          "bd" '(kill-current-buffer :wk "[b]uffer [d]elete")
          "br" '(revert-buffer :wk "[b]uffer [r]eload(revert)"))

      ;; bookmark
      (dobin/leader-keys
          "m" '(:ignore t :wk "book[m]ark")
          "ms" '(bookmark-set :wk "[b]ookmark [s]et")
          "mj" '(bookmark-jump :wk "[b]ookmark [j]ump"))

      ;; universal argument
      (dobin/leader-keys
          "u" '(universal-argument :wk "[u]niversal prefix")) ;; C-u의 원래 기능을 리더키로 사용

      (dobin/leader-keys
          "ere" '("restart emacs" . (lambda () (interactive) (restart-emacs))))

      ;; org
      (dobin/leader-keys
          "o" '(:ignore t :wk "[o]rg"))
      )
#+end_src

** TODO delsel
뭔지 잘 모르겠음. 확인 필요
#+begin_src emacs-lisp :lexical t
  (use-package delsel
      :ensure nil
      :config
      (delete-selection-mode t))
#+end_src

** org


#+begin_src emacs-lisp :lexical t
  (use-package org
      :ensure (:wait t)
      :demand t
      :config
      (add-to-list 'org-structure-template-alist '("S" . "src emacs-lisp :lexical t\n"))
      :custom
      (org-auto-align-tags nil)
      (org-directory (concat dobin/org-path "agenda"))
      (org-default-notes-file (concat org-directory "/notes.org"))
      :general
      (org-mode-map
          "C-s" 'consult-org-heading)
      (dobin/leader-keys
          "oa" '("[a]genda" . org-agenda)
          "oc" '("[c]apture" . org-capture)
          "ol" '("store [l]ink" . org-store-link)
          )
      (dobin/local-leader-keys
          :keymaps 'org-mode-map
          "<" '("up one heading" . org-up-heading)
          "a" '("[a]genda" . org-agenda)

          "b" '(:wk "[b]abel" :ignore t )
          "bt" '("[t]angle" . org-babel-tangle)

          "c" '("[c]apture" . org-capture)

          "e" '("edit" . org-edit-special)

          "i" '(:ignore t :wk "[i]nsert")
          "ih" '(:ignore t :wk "[h]eading")
          "ihh" '("[h]eading" . org-insert-heading)
          "ihS" '("[S]ub heading" . org-insert-subheading)
          "iht" '("[t]odo" . org-insert-todo-heading)
          "ihT" '("[T]odo subheading" . org-insert-todo-subheading)

          "is" '("[s]tructure template" . org-insert-structure-template )

          "l" '("store [l]ink" . org-store-link )
          )
      (dobin/local-leader-keys
          :keymaps 'org-src-mode-map
          "s" '("save and quit edit buffer" . org-edit-src-exit))
      )
#+end_src

*** TODO org-roam
노트 관리 도와주는 패키지. 사용법 알아봐야함

#+begin_src emacs-lisp :lexical t
  (use-package org-roam
      :ensure t
      :demand t
      :general
      (dobin/leader-keys
          "n" '(:ignore t :wk "[n]otes(roam)")
          "ni" '("node [i]nsert" . (lambda () (interactive) (org-roam-node-insert t)))
          )
      :custom
      (org-roam-directory dobin/notes-path)
      )
#+end_src
** paren
괄호 관련 표시 설정

#+begin_src emacs-lisp :lexical t
  (use-package paren
      :custom
      (show-paren-delay 0)
      (show-paren-style 'expression)
      (show-paren-when-point-in-periphery t)
      (show-paren-when-point-inside-paren t)
      :config
      (show-paren-mode +1))
#+end_src

** TODO avy
vim-easymotion의 evil 버전?
hint key의 변경법을 알아봐야할 필요가 있음.

#+begin_src emacs-lisp :lexical t
  (use-package avy
    :ensure t
      :custom
      (avy-keys '(?n ?r ?t ?s ?h ?a ?e ?i))
    :general
    (:states '(normal motion)
        "s" 'evil-avy-goto-char-timer
        "f" 'evil-avy-goto-char-in-line
        "gl" 'evil-avy-goto-line
        )
    )
#+end_src

** vterm

이맥스에서 터미널을 사용하기 위한 패키지인데 windows에서 안되고 fish도 제대로 컬러가 로딩이 안돼서 그냥 터미널을 사용할 예정이라 비활성화 해놓았다.

#+begin_src emacs-lisp :lexical t
  (use-package vterm
      :ensure nil
      :disabled)
#+end_src
** doom-modeline

modeline인데 설정하기는 당장에 귀찮아서 일단 꽨찮아보이는 doom-modeline을 사용했다.

#+begin_src emacs-lisp :lexical t
  (use-package doom-modeline
      :ensure t
      :init
      (doom-modeline-mode +1))
#+end_src

** recentf
최근 방문한 파일을 관리하는 패키지.

#+begin_src emacs-lisp :lexical t
  (use-package recentf
      :ensure nil
      :custom
      (recentf-mode +1)
      :general
      (dobin/leader-keys
          ;; "fr" '(recentf-open :wk "Show [r]ecent files")
          "f." '(recentf-open-most-recent-file :wk "open last(.) file"))
      )
#+end_src


** consult
검색 및 이동을 도와주는 패키지
#+begin_src emacs-lisp :lexical t
  (use-package consult
      :ensure t

      :general
      ([remap goto-line] 'consult-goto-line)
      ([remap Info-search]  'consult-info)
      (dobin/leader-keys
          "bs" '("[s]witch" . consult-buffer)

          "fr" '("[r]ecent" . consult-recent-file)

          "sg" '("[g]rep" . consult-grep)
          )

      :init
      (advice-add #'register-preview :override #'consult-register-window)

      :custom
      (register-preview-delay 0.5)
      )
#+end_src

** embark
추가행동?을 할 수 있게 해주는 패키지인데 아직은 사용 할 타이밍을 잘 못잡고있다.
#+begin_src emacs-lisp :lexical t
    (use-package embark
        :ensure t

        :config
        (general-define-key
            "C-," 'embark-act)
        (add-to-list 'display-buffer-alist
            '("\\`\\*Embark Collect \\(Live\\|Completions\\)\\*"
                 nil
                 (window-parameters (mode-line-format . none)))))
#+end_src

** embark-consult
=embark= 와 =consult= 를 연계시켜주는 패키지. 설치하지 않으면 같이 사용할 수 없다는 경고가 뜬다.

#+begin_src emacs-lisp :lexical t
  (use-package embark-consult
      :ensure t)
#+end_src

** marginalia
minibuffer에서 항목에 대한 설명을 추가한다.
일단은 =M-x= 에서 작동하는 건 확인했음.

#+begin_src emacs-lisp :lexical t
    (use-package marginalia
        :ensure t
        :config
        (marginalia-mode))
#+end_src

** which-key
neovim에서도 유명한 패키지의 원본 현재 입력된 키에서 수행할 수 있는 액션들을 보여준다.

#+begin_src emacs-lisp :lexical t
  (use-package which-key
      :after evil
      :demand t
      :init
      (which-key-mode 1)
      :config
      ;; (which-key-setup-minibuffer)
      (which-key-setup-side-window-bottom)
      )
#+end_src

** catppuccin
늘 사용하는 테마.

#+begin_src emacs-lisp :lexical t
    (use-package catppuccin-theme
        :ensure t
        :demand t
        ;; :hook (server-after-make-frame . catppuccin-reload)
        :config
        (load-theme 'catppuccin :no-confirm))
#+end_src

** Treesitter
프로그래밍 언어에 맞는 문법
#+begin_src emacs-lisp :lexical t
  (use-package tree-sitter :ensure t :demand t :config (global-tree-sitter-mode))

  (use-package tree-sitter-langs :ensure t :demand t)
#+end_src

*** Nix

#+begin_src emacs-lisp :lexical t
  (use-package nix-ts-mode
      :ensure t
      :mode "\\.nix\\'")
#+end_src

** rainbow delimiter

괄호의 색을 변경해서 몇 번 중첩이 됐는 지 알려준다.
#+begin_src emacs-lisp :lexical t
  (use-package rainbow-delimiters
      :ensure t
      :hook (prog-mode . rainbow-delimiters-mode))
#+end_src

** command-log-mode

사용한 커맨드가 무엇인지 확인할 수 있는 패키지. 주로 지금 누른 키가 무슨 명령어를 불렀는 지 확인하는 용도로 사용했다.
#+begin_src emacs-lisp :lexical t
  (use-package command-log-mode
      :ensure t)
#+end_src

** 자동완성
=corfu= =cape= =orderless= =vertico=

#+begin_src emacs-lisp :lexical t
#+end_src

*** corfu

기본 에디팅에서 사용하는 자동완성
#+begin_src emacs-lisp :lexical t
  (use-package corfu
      :ensure t
      :hook (prog-mode . (lambda () (setq-local corfu-auto t)))
      :init
      (global-corfu-mode)
      :custom
      (corfu-auto-prefix 2)
      (corfu-cycle t)
      :config
      (keymap-unset corfu-map "RET")
      )
#+end_src

*** vertico

minibuffer 에서 사용하는 자동완성
#+begin_src emacs-lisp :lexical t
  (use-package vertico
      :ensure t
      :init (vertico-mode))
#+end_src

*** orderless

자동완성에서 fuzzy 매칭을 사용하기 위해 사용하는 패키지. 다양하게 필터링이 가능하다.
#+begin_src emacs-lisp :lexical t
  (use-package orderless
      :ensure t
      :custom
      (orderless-matching-styles 'orderless-flex)
      (completion-styles '(orderless partial-completion basic))
      (completion-category-defaults nil)
      (completion-category-overrides '((file (styles partial-completion)))))
#+end_src

*** cape

#+begin_src emacs-lisp :lexical t
  (defun dobin/elisp-mode-init ()
      "Set completion function to cape"
      (setq-local completion-at-point-functions
  	    (list (cape-capf-inside-code #'cape-elisp-symbol))))
  (add-hook 'emacs-lisp-mode-hook #'dobin/elisp-mode-init)

  (use-package cape
      :ensure t)
#+end_src

*** dabbrev

#+begin_src emacs-lisp :lexical t
  (use-package dabbrev
      :bind (("M-/" . dabbrev-completion)
  	          ("C-M-/" . dabbrev-expand))
      :config
      (add-to-list 'dabbrev-ignored-buffer-regexps "\\` ")
      (add-to-list 'dabbrev-ignored-buffer-modes 'authinfo-mode)
      (add-to-list 'dabbrev-ignored-buffer-modes 'doc-view-mode)
      (add-to-list 'dabbrev-ignored-buffer-modes 'pdf-view-mode)
      (add-to-list 'dabbrev-ignored-buffer-modes 'tags-table-mode))

#+end_src


*** lsp-mode

lsp와 연결하기 위한 패키지. 설정하는 방법을 잘 모르겠다.
#+begin_src emacs-lisp :lexical t
  (use-package lsp-mode
      :ensure t
      :commands lsp
      :custom
      (lsp-completion-provider :none)
      (lsp-keymap-prefix "C-c l")
      :hook
      (lsp-mode . lsp-enable-which-key-integration)
      (nix-ts-mode . lsp)
      :init
      (defun dobin/orderless-dispatch-flex-first (_pattern index _total)
          (and (eq index 0) 'orderless-flex))

      (defun dobin/lsp-mode-setup-completion ()
          (setf (alist-get 'styles (alist-get 'lsp-capf completion-category-defaults))
  	        '(orderless))
          (setq-local orderless-style-dispatchers (list #'dobin/orderless-dispatch-flex-first))
          (setq-local completion-at-point-functions (list (cape-capf-buster #'lsp-completion-at-point))))
      :hook
      (lsp-completion-mode . dobin/lsp-mode-setup-completion))

  (use-package lsp-ui :ensure t :commands lsp-ui-mode
      :custom
      (lsp-ui-sideline-show-hover t))
#+end_src

*** kind-icon

자동완성에서 아이템의 유형이 뭔지 알려주는 패키지

#+begin_src emacs-lisp :lexical t
  (use-package kind-icon
      :ensure t
      :after corfu
      :config
      (add-to-list 'corfu-margin-formatters #'kind-icon-margin-formatter))
#+end_src

* 폰트

D2Coding Nerd Font의 Mono는 글자 폭이 잘못 설정되어 있어서 사용할 시 영어의 폭과 맞춰지기 때문에 일반 폰트로 사용해야한다.
- 출처 : https://codepractice.tistory.com/167
#+begin_src emacs-lisp :lexical t
  (defun dobin/set-korean-font (frame)
      "Set font for new frames"
      (when (display-graphic-p frame)
          (with-selected-frame frame
              (set-fontset-font "fontset-default" 'hangul (font-spec :family "D2CodingLigature Nerd Font" :size 18)))))
  (add-hook 'after-make-frame-functions 'dobin/set-korean-font)

  (set-face-attribute 'match nil :background "#74c7ec" :foreground "#1e2030")

  (add-to-list 'default-frame-alist '(font . "JetBrainsMono NF-14"))
#+end_src

* 커스텀 | Custom

직접 만들거나 블로그 등에서 긁어온 함수나 변수. 기능을 보완하는 데 사용하고 있다.

#+begin_src emacs-lisp :lexical t
  (defun dobin/keyboard-quit ()
      "Smarter version of the built-in `keyboard-quit'."
      (interactive)
      (if (active-minibuffer-window)
          (if (minibufferp)
  	        (minibuffer-keyboard-quit)
  	        (abort-recursive-edit))
          (keyboard-quit)))
  (global-set-key [remap keyboard-quit] #'dobin/keyboard-quit)

#+end_src

** save and quit (ZZ)

=evil-save-modified-and-quit= 과 같은 기능인데 존재를 알기 전에 만들어서 그냥 쓰고 있다.
=M-w= 에 설정에서 사용 중
#+begin_src emacs-lisp :lexical t
  (defun dobin/save-and-kill-buffer ()
      "현재 버퍼를 저장하고 제거"
      (interactive)
      (save-buffer)
      (evil-quit))
#+end_src

** restart daemon

=restart-emacs= 를 사용하면 daemon이 랜덤하게 뻗는 현상이 있어서 systemctl로 서비스 자체를 재시작하는 방법을 사용한다.

#+begin_src emacs-lisp :lexical t
  (defun dobin/restart-server ()
      (interactive)
      (save-buffer )
      (shell-command "systemctl --user restart emacs.service"))
#+end_src
